motis-project/nigiri

include/nigiri/loader/gtfs/local_to_utc.h
include/nigiri/routing/raptor.h
src/loader/build_footpaths.cc
src/loader/gtfs/stop.cc
src/routing/dijkstra.cc
src/routing/raptor.cc
src/routing/reconstruct.cc

- fix reconstruction:
- checked if first leg start is meta to start station
- then required that start station is meta to leg start
- thereby assumed symmetric equivalence relation, which is not the case
- fixed check to be consistent
- in GTFS some services have a start time of >24:00 which implies they operate the next day
- when checking if a service is active the service operating time interval (in days) contained also the first day (before 24:00) - but here, the service is not active and should therefore not be loaded (to be consistent with MOTIS)
- lower bound initialization was not considering equivalent stations, now it does

fixes: reconstruction for station-station, GTFS trips with first dep>24:00, lb init

---

include/nigiri/common/linear_lower_bound.h
include/nigiri/routing/raptor/raptor.h

| Version | Average | q99 | q90 | q80 | q50 |
| ----------------- | ------------- |------------- |------------- |------------- |------------- |
| Binary Search | 830 ms  | 2,661 ms | 1,544 ms  |  1,218 ms   | 676 ms |
| No Seek          | 815 ms  | 2,645 ms | 1,506 ms  |   1,197 ms  | 659 ms |
| Linear Seek    | 793 ms   | 2,478 ms | 1,484 ms |   1,150  ms | 639 ms |
```ini
modules=nigiri
modules=intermodal
modules=osrm
mode=batch
num_threads=12
dataset.no_schedule=true
intermodal.router=nigiri
osrm.profiles=/home/felix/code/motis/deps/osrm-backend/profiles/foot.lua
[import]
paths=schedule-nl:input/schedule/nl
paths=schedule-delfi:input/schedule/delfi
paths=schedule-swiss:input/schedule/swiss
paths=osm:input/osm.pbf
[nigiri]
geo_lookup=true
first_day=2023-05-16
num_days=14
```

use linear lower bound instead of std::lower_bound

---

include/nigiri/abi.h
include/nigiri/rt/rt_timetable.h
include/nigiri/types.h
server/main.cc
src/abi.cc
src/clasz.cc
src/rt/gtfsrt_update.cc
test/abi_test.cc

As discussed previously, this PR enables a limited subset of nigiri to be used by other non C++ code. This is just a draft as a basis for further discussion. I have no experience in C++ whatsoever, so please review carefully.
As an example, the wrapping Rust crate(s) I have created are available at [traines-source/motis-nigiri-rust](https://github.com/traines-source/motis-nigiri-rust).
A couple of decisions/questions that need discussion:
1. I have decided to create a pure C wrapper that then can be wrapped by the C-ABI compatible language of your choice. While it is possible to have other programming languages interface with C++ directly, this is usually not recommended (see e.g. [here](https://stackoverflow.com/a/75556744/1666456) and …

Provide an ABI to enable projects written in other languages to use nigiri as a lib

---

include/nigiri/types.h

This fixes a heap overflow when loading the current Transitous dataset.
Fixes https://github.com/public-transport/transitous/issues/81.

Increase timezone index to 16bit

---

include/nigiri/routing/limits.h

Greatly improves tail latency for transitous dataset
**Baseline**
```
--- total_time --- (n = 100)
25%: (t_total:    2.829s, t_exec:    2.656s, intvl_ext:  0, intvl_size:    5h, #jrny:  5)
50%: (t_total:   10.471s, t_exec:   10.272s, intvl_ext:  1, intvl_size:   15h, #jrny:  7)
75%: (t_total:   69.797s, t_exec:   69.622s, intvl_ext:  4, intvl_size:  912h, #jrny:  0)
90%: (t_total:  312.451s, t_exec:  312.270s, intvl_ext:  4, intvl_size:  912h, #jrny:  0)
99%: (t_total:  605.199s, t_exec:  605.030s, intvl_ext:  4, intvl_size:  912h, #jrny:  0)
99.9%: (t_total:  605.199s, t_exec:  605.030s, intvl_ext:  4, intvl_size:  912h, #jrny:  0)
max: (t_total:  605.199s, t_exec:  605.030s, intvl_ext:  4, intvl_size:  912h, #jrny:  0)
----------------------------------
```
**5 days, 15 transfers**
``` …
```

increase kMaxTransfers to 15, increase kMaxTravelTime to 5 days

---

include/nigiri/query_generator/generator_settings.h
include/nigiri/routing/query.h
include/nigiri/types.h

- changes the default value for `use_start_footpaths` to `false`
- adds a comment that explains the relation between search direction and user perspective

Start footpaths

---

include/nigiri/shape.h
src/shape.cc

Making the creation mode optional allows clients to load stored data without duplicating this function. This is especially useful if import and usage can run independently.
For instance, it could be applied to motis-project/motis#537 immediately to remove duplicated code.

Allow optional creation mode

---

src/routing/start_times.cc
test/routing/start_times_test.cc

Addresses the first point of Suspicious Code #121

Skip RT start times outside the search interval

---

test/loader/gtfs/stop_time_test.cc
test/loader/gtfs/test_data.cc

The test data contained an additional column, that didn't correspond to any header.
For the changed test, I think this is the intended use case, as `pickup_type == 0` is checked multiple times.

Fix test data for 'stop_times.txt'

---

src/loader/gtfs/shape_prepare.cc
src/rt/frun.cc
test/rt/frun_shape_test.cc

Fixes an issue, where `frun::for_each_shape_point()` could invoke supplied callback for only a single coordinate.
This issue is now checked by:
* Always invoke callback for start and end stop
* Ensure no duplicated shape offsets are calculated and stored

Fix incomplete segments

---

include/nigiri/common/delta_t.h
test/delta_t_test.cc

old version (not what you would expect):
auto [day, mam] = split_day_mam(day_idx_t{10}, delta_t{-1440});
EXPECT_EQ(day, day_idx_t{8});
EXPECT_EQ(mam.count(), 1440);
now:
auto [day, mam] = split_day_mam(day_idx_t{10}, delta_t{-1440});
EXPECT_EQ(day, day_idx_t{9});
EXPECT_EQ(mam.count(), 0);

fix split for negative whole day deltas

---

include/nigiri/rt/frun.h
src/rt/frun.cc

Add a function to invoke a given callback for each trip of a `frun` object.
This can be useful when performing calculations on shape segments, e.g. per segment bounding boxes.

Implement callback invocation for each trip

---

include/nigiri/routing/raptor/raptor.h

Before: At the end of a connection, timetable footpaths could be used to reach other stations + intermodal footpaths from these other stations to the destination.
After: Timetable footpaths can no longer be used directly before intermodal footpaths at the end.

Expand intermodal footpaths before other footpaths

---

src/loader/gtfs/shape_prepare.cc
src/loader/gtfs/stop_time.cc
test/loader/gtfs/service_test.cc

Using a GTFS feed, that is missing a 'stop_id' in 'stops.txt', could led to a buffer overflow when creating bounding boxes.

Fix buffer overflow when creating bounding boxes

---

include/nigiri/routing/search.h
include/nigiri/routing/transfer_time_settings.h
test/routing/transfer_time_settings_test.cc

This adds an option to increase the time between transfers by a fixed duration. This setting can be used, if passengers want some time for orientation or to compensate small delays.

Add setting for disposable time between transfers

---

src/loader/gtfs/trip.cc

Fixes https://github.com/motis-project/motis/issues/671
The fundamental issue is that the GTFS file specifies a 59 second headway, which will be converted to minute granularity by dividing by 60. The / operator on integers truncates towards zero, so we end up with a 0 headway. 
This then makes `number_of_iterations` divide by zero.
for exact_times != 1, properly rounding should be good enough as long as we don't end up with zero.

Fix loading GTFS frequencies with < 60 seconds headway

---

include/nigiri/routing/raptor/raptor.h
src/routing/raptor/reconstruct.cc
test/routing/via_search_test.cc

Fixes the following bugs in the via search implementation that caused reconstruction errors:
- If a trip passing a via stop has in/out allowed = false at the via stop, reconstructing the journey failed.
- Queries where the last via stop is also a destination and has a non-zero stay duration were not handled properly. They are now handled as follows:
- Intermodal destination (probably the only useful case): Stay duration at the last stop is added as waiting time between the arrival + start of the intermodal footpath. Transfer time at the last stop is ignored.
- Station destination: Stay duration at the last stop is ignored (i.e. same result as if stay = 0 in the query). The stay duration can't be properly represented in the output journey in this case, but this doesn't seem like a useful …

Via search fixes

---

src/rt/gtfsrt_update.cc

Previously all messages containing unsupported fields like (alert or
vehicle) were ignored, even if they contained an understandable
trip_update.
Now all possible warnings are emitted, not just the first fatal one.
This commit also changes the debug output to show the names of the
relevant fields to make it easier to debug GTFS-RT feeds without looking
at the MOTIS source code.

Don't drop partially unsupported GTFS-RT messages

---

include/nigiri/abi.h
include/nigiri/rt/rt_timetable.h
src/abi.cc
src/rt/gtfsrt_update.cc
src/rt/vdv/vdv_update.cc
test/abi_test.cc

This finally addresses most of the open todos from #66, among other things:
* handle RT track changes, in_allowed/out_allowed
* expose footpaths
* expose querying/journeys
There is one change I made that has an impact outside of the ABI: For absolute-time-based GTFSRTs (`ev.has_time()`), the time-travel-corrected time will be propagated in [L119](https://github.com/traines-source/nigiri/blob/aa4c837b46b62f69d94295d9cf92d2c2ad13bfa2/src/rt/gtfsrt_update.cc#L119) just like for delay-based GTFSRTs in [L94](https://github.com/traines-source/nigiri/blob/aa4c837b46b62f69d94295d9cf92d2c2ad13bfa2/src/rt/gtfsrt_update.cc#L94). I think this was a bug.

Extend ABI to expose journeys, footpaths, cancellations

---

src/rt/gtfsrt_update.cc
test/rt/gtfsrt_relative_test.cc
test/rt/gtfsrt_rt_test.cc

As discussed previously in the Transitous channel, time travel is not fixed by nigiri under certain circumstances, e.g. [in this DELFI RT feed update from today 18:06](https://stc.traines.eu/mirror/german-delfi-gtfs-rt/2025-01-01/2025-01-01T18%3A06%3A03%2B01%3A00.gtfs-rt.pbf) ([archive](https://mirror.traines.eu/german-delfi-gtfs-rt/2025-01-01.tar.bz2)) for `trip_id` 2716892734:
```
{
"id":"2716892734",
"trip_update":{"trip":{"trip_id":"2716892734","start_time":"22:11:00","start_date":"20250101","schedule_relationship":0,"route_id":"de:aac:05334|51:aseag_3"},
"stop_time_update":[
{"stop_sequence":2,"arrival":{"delay":-15887},"departure":{"delay":-15887},"stop_id":"de:05334:1177:1:1","schedule_relationship":0},
{"stop_sequence":5,"arrival":{"delay":-15917},"departure":{"delay":-15917},"stop …
```

time-travel-robustness at beginning of trips

---

CMakeLists.txt

As the `main.cc` file targeted here has been removed/refactored to be part of some other target, this lets the build fail, if no target is specified and can be removed

Remove unavailable/unused cmake target

---

src/loader/gtfs/trip.cc

Related to https://github.com/public-transport/transitous/issues/886

Improve trip display name

---

include/nigiri/routing/one_to_all.h
src/routing/one_to_all.cc
test/rt/frun_shape_test.cc

Simplifies the One-to-All API, as discussed in motis-project/motis#783.

Make One-to-All template parameter a regular parameter

---

include/nigiri/routing/raptor/raptor.h

This fixes an error, that prevented compiling with `NIGIRI_TRACING` defined.
I suppose, that this should be the intended behavior, as it matches the previous debug output:
https://github.com/motis-project/nigiri/blob/21332e241bbf4b9bb2ba3c7672495bca13936e29/include/nigiri/routing/raptor/raptor.h#L713-L716
I also found some instances, where the time could be displayed formatted for better readability. If you prefer the current format, I can revert these changes.

Fix trace debug build

---

src/routing/raptor/reconstruct.cc

If a footpath were to be delayed, as a path is temporary blocked, e.g. due to elevator maintenance, the reconstruction failed to find the previous location. This should fix this issue.

Fix reconstruction when delayed by blocked path

---

include/nigiri/loader/gtfs/local_to_utc.h
src/loader/gtfs/trip.cc
test/loader/gtfs/stop_time_test.cc
test/rt/gtfsrt_resolve_trip_test.cc

I stumbled upon "Floating point exception (core dumped)" on import, probably same as [this](https://github.com/motis-project/motis/issues/694#issuecomment-2575660882).
Wasn't able to reproduce again, but I suspect this issue in `trip.cc` could be the cause, since divisions by zero do seem to happen there, e.g. when the first `arrival_time` is undefined, which I think I have seen in the wild before (the `utl::verify`s don't seem to do what they promise).

fix floating point exception

---

include/nigiri/loader/gtfs/route_key.h
include/nigiri/loader/gtfs/trip.h
include/nigiri/loader/loader_interface.h
include/nigiri/routing/query.h
include/nigiri/routing/raptor/raptor.h
include/nigiri/routing/search.h
include/nigiri/rt/frun.h
include/nigiri/rt/rt_timetable.h
include/nigiri/timetable.h
src/clasz.cc
src/loader/gtfs/load_timetable.cc
src/loader/gtfs/trip.cc
src/loader/hrd/service/service_builder.cc
src/routing/one_to_all.cc
src/routing/raptor/reconstruct.cc
src/rt/frun.cc
src/rt/rt_timetable.cc
test/loader/gtfs/stop_time_test.cc
test/loader/gtfs/trip_test.cc
test/raptor_search.cc
test/raptor_search.h
test/routing/wheelchair_assistance_test.cc

Adds support for traveling with a car (based on #108):
- GTFS: cars_allowed field in trips.txt is now parsed. This is currently not yet in the GTFS standard, but a proposed addition (https://github.com/google/transit/pull/547).
- For trips with cars_allowed = 0 or no car information, a default value based on the route clasz is used (defaults can be specified in loader_config).
- Added a new require_car_transport_ flag to routing::query. If set to false (the default value), returns the same results as before. If set to true, only trips where cars are allowed can be used.

Car transport

---

src/loader/gtfs/stop.cc

This pr adds the ability to import GTFS stops that have a platform_code, but no parent_station. It does this by creating artificial parents which hold the station's name, as motis locations only have name and id but no field for track information. 
stops.txt entries with platform_code but no parent_station is not inline with the GTFS spec, but common practice at least for the Delfi feed. With this pr we strengthen the import to support track data, even if it's a bit out of spec.

Add support for importing platform_code of stations/stops without a parent

---

src/fares.cc
src/loader/gtfs/fares.cc

While not directly related to https://github.com/motis-project/motis/issues/906, another place where undefined fare products might create problems. Haven't actually verified the behavior.

invalid fare product fallback

---

include/nigiri/rt/vdv_aus.h
src/rt/vdv_aus.cc
test/rt/vdv_aus_test.cc

- stricter threshold for additional matches to prevent false positives in case of low headway: 0.9 --> 0.975
- improved event time matching: 1st stop: match dep, last stop: match arr, else: match any

VDV AUS: Tweaks

---

include/nigiri/routing/query.h
src/routing/direct.cc

or do we need something more sophisticated, because this way, if there is one very fast direct connection, other "relevant" connections at other times will be removed... But the pareto-optimal ones should still be there, so...

fix slowDirect for loop lines

---

src/loader/merge_duplicates.cc
test/loader/merge_duplicates_test.cc

This fixes an error, that caused merged trips to contain less traffic days than intended.
Is modification of this test fine? Or does this break something else, that I'm missing right now?

Fix incorrect traffic days after merge

---

src/loader/register.cc

This matters for global code in the script calling library functions, most notably `require`.

Load Lua libraries before loading the import script

---

include/nigiri/logging.h
src/logging.cc

This changes the scope of `nigiri::s_verbosity`, to work with motis-project/motis#971.
Not sure why I didn't notice this before. But this will make it aligned with [`utl::log_verbosity`](https://github.com/motis-project/utl/blob/master/include/utl/logging.h#L27).
Does the variable needs to be renamed, as done for `utl::log_verbosity` (https://github.com/motis-project/utl/commit/b4d6a1be9635a246e6f2c90d5dcd1cc698087843)?

Fix log_lvl not updating
